# Generated by Django 3.1.8 on 2021-09-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='data',
            field=models.DateField(default='2021-09-15'),
            preserve_default=False,
        ),
    ]
